[package]
name = "liketrain-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chumsky = "0.12.0"
thiserror = "2"

liketrain-hardware = { path = "../liketrain-hardware" }
serialport = "4.8.1"
crossbeam = "0.8.4"

itertools = "0.14.0"
log = "0.4.29"

[dev-dependencies]
env_logger = "0.11.9"
